services:
  nginx:
    image: nginx:alpine
    networks:
      - ams-network
    ports:
      - "19876:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ams_frontend
      - ams_backend

  ams_frontend:
    networks: 
      - ams-network
    build: ./front
    environment:
      - NODE_ENV=production

  ams_backend:
    networks: 
      - ams-network
    build: ./back
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - KOREA_INVESTMENT_APPKEY=${KOREA_INVESTMENT_APPKEY}
      - KOREA_INVESTMENT_APPSECRET=${KOREA_INVESTMENT_APPSECRET}
    restart: always
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:prod
      "
    volumes:
      - ./back/.env:/app/.env
    env_file:
      - ./back/.env

  db:
    networks: 
      - ams-network
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/ams/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ams-network:
    name: ams-network
    driver: bridge
    
volumes:
  postgres_data: