services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://dec:Abraham1!@db:5432/stockdb
    restart: always
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run dev
      "

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dec
      POSTGRES_PASSWORD: Abraham1!
      POSTGRES_DB: stockdb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dec -d stockdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: