-- AlterTable
ALTER TABLE "stock" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "assetClass" DROP DEFAULT,
ALTER COLUMN "account" DROP DEFAULT,
ALTER COLUMN "excd" DROP DEFAULT;
